remote_theme: al-folio@master
plugins:
- jekyll-remote-theme

title: Cat Classifier
description: An image classification API that can classify 20 different breeds of cats

author: 
  name: Md Maruf Chowdhury